### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by sciurius** [jerheij/docker-spotweb#16]
When I use the example as docker-compose.yml I get the error:

````
$ docker-compose up
ERROR: Named volume "config/dbsettings.php:/var/www/spotweb/dbsettings.inc.php:rw" is used in service "spotweb" but no declaration was found in the volumes section.
````

**Comment by jerheij** [comment]
> When I use the example as docker-compose.yml I get the error:
> 
> ```
> $ docker-compose up
> ERROR: Named volume "config/dbsettings.php:/var/www/spotweb/dbsettings.inc.php:rw" is used in service "spotweb" but no declaration was found in the volumes section.
> ```

Hey, have you performed the **initial installation** step from the readme to create and then copy the dbsettings file?

**Comment by sciurius** [comment]
Yes, the initial installation runs ok.

> The best way is to copy that file to your config folder

I must admit I'm a docker novice...  What file? What config folder?

**Comment by jerheij** [comment]
> Yes, the initial installation runs ok.
> 
> > The best way is to copy that file to your config folder
> 
> I must admit I'm a docker novice... What file? What config folder?

Basically the **initial installation** runs the container and when you go through the installation steps it will create `/var/www/spotweb/dbsettings.inc.php` inside the container.

You then need to copy the file with a `docker copy` command to outside the container.

Then you need to link the location of that dbsettings file when starting the container inside the docker-compose.yaml file.

**Comment by sciurius** [comment]
Ah! That was the missing link. Thanks!

**Comment by jerheij** [comment]
> Ah! That was the missing link. Thanks!

Great, hope you're all sorted!
