### ISSUE TITLE
package php7-pdo_pgsql missing to support psql db

### ISSUE THREAD

**Issue by lassieee** [jerheij/docker-spotweb#2]
Hi,
I came across your spotweb image on docker hub, and decided to give it a try. I was unable to use a postgres database, because of a missing database driver:

![Screenshot from 2020-09-05 23-08-19](https://user-images.githubusercontent.com/4531126/92313519-df7b7b80-efcc-11ea-8ab9-82d45fff04e2.png)

![Screenshot from 2020-09-05 23-10-19](https://user-images.githubusercontent.com/4531126/92313530-0639b200-efcd-11ea-9e4a-a7df05bbe2b1.png)

After cloning your repo and adding the package 'php7-pdo_pgsql' to the 'apk add' command in your dockerfile, I was able to successfully use a postgres database. I thought I'd let you know so you could update your image :-)

Cheers,
Casper

**Comment by lassieee** [comment]
well, it seems the installation is succesfull, but the spotweb gui is all messed up, css issues perhaps? I tried with both the github spotweb master and develop branch and docker images postgres:12.4-alpine, 11.9-alpine, 10.14-alpine, 9.6.19-alpine and even tried with php5, but it seems there is no php5-mbstrings.
Using a mysql database is succesfull and the gui looks the way it should.
Enough spotweb for me for tonight..

**Comment by jerheij** [comment]
> 
> After cloning your repo and adding the package 'php7-pdo_pgsql' to the 'apk add' command in your dockerfile, I was able to successfully use a postgres database. I thought I'd let you know so you could update your image :-)
> 
> Cheers,
> Casper

Thanks for letting me know! 

Thats weird though... It should technically only effect the database connection, not the interface itself. I'll have a look later today.

**Comment by lassieee** [comment]
hmm, it seems the issue with the malformed layout has to do with me running spotweb behind a Traefik reversed proxy. I tried a spotweb image from a different developer which didn't have the issue. I'll see if I can find out why that is. I really want posgres for my spotweb instance :-)

**Comment by jerheij** [comment]
I think it was a problem in my latest image build. I have tested around by adding a test.php (check out my test branch) and it worked. Then I rebuild my docker image from my regular branch and it works as well.

For your information; the right SQL driver is being installed in the entry.sh, not in the Dockerfile, I did this to keep the image as lean as possible and without unnecessary PHP modules running as well. I have updated to a new update tag (_1.1.0-u2_), which is also the _stable_ tag, and it seems to work for me. All the drivers show up as OK when choosing the right one in the **docker run** command or in the docker-compose.yml file.

Let me know if you still find any issues!

**Comment by lassieee** [comment]
ah yes, I missed that. I did notice the entry.sh file, but I must've read past the php7-pdo_pgsql package.. Sorry
I just tried your 1.1.0-u2 image and all the drivers work out great. Thanks! I tried again with the 1.1.0-u1 image and indeed, it is an issue with that build.

I found out about the messed up css. I have a couple services running behind Traefik, which automagically get LetsEncrypt certificates for all my services. The css is only "broken" when I redirect to https (which I do for all my services).

For nginx this can be fixed by adding a ssl override parameter. The solution for nginx is this: https://github.com/edv/docker-spotweb/commit/ecd7da4a49c01c618410f40cf2516720e9ff87d6
Or by adding a ownsettings.php in the spotweb root with the content:
<?php
   $settings['ssloverride'] = true;
?>
see https://github.com/spotweb/spotweb/wiki/Installation-tips-and-troubleshooting

Not sure how that works for apache2 though, I'll look into that later and let you know what I find out.

Thank you for your time.

**Comment by jerheij** [comment]
> ah yes, I missed that. I did notice the entry.sh file, but I must've read past the php7-pdo_pgsql package.. Sorry
> I just tried your 1.1.0-u2 image and all the drivers work out great. Thanks! I tried again with the 1.1.0-u1 image and indeed, it is > an issue with that build.

I will remove the 1.1.0-u1 image from hub.docker.com to prevent people from using that image.

> I found out about the messed up css. I have a couple services running behind Traefik, which automagically get LetsEncrypt certificates for all my services. The css is only "broken" when I redirect to https (which I do for all my services).
> 
> For nginx this can be fixed by adding a ssl override parameter. The solution for nginx is this: edv/docker-spotweb@ecd7da4
> Or by adding a ownsettings.php in the spotweb root with the content:

I haven't used this with another reverse proxy than nginx. I have a simple nginx container I use as frontend for all my webservices, it has worked perfectly so far.

> Thank you for your time.

No problem at all! I probably wouldn't have noticed it for a while since I currently don't use spotweb for a while, even back when I did use it, it was in combination with a mysql database. So thanks again for notifying me!
