### ISSUE TITLE
retrieve.php scheduling?

### ISSUE THREAD

**Issue by LeeThompson** [jerheij/docker-spotweb#6]
One thing not mentioned anywhere is the running of the retrieve.php script which is how spotweb gets it's data.    

Does this docker image include a crontab for this?

If not, is there a way to set it up with a volume/file mount so that it persists with container image updates?

(What would be awesome is if the schedule and various retrieve settings could be passed in with environment variables.)

**Comment by jerheij** [comment]
I currently don't use this image myself any more (I still keep it updated though) but what I did when using it before is running a cronjob from the docker node which runs the retrieve.php.

You are correct though about it not being mentioned somewhere in the readme but I think it is mentioned in the documentation from the application itself. But I should mention it somewhere in the documentation. The current docker image does not have a crontab included either.

However @NorthGuy just contributed by creating a pull request ( #5 ) with this functionality included. I will look at this shortly and most likely merge it into the master branch to add this functionality. I will then create a specifically tagged container image with this functionality included and if you want you can test it as well.

**Comment by jerheij** [comment]
I have merged the pull request into the master branch. You should be able to use either `SPOTWEB_CRON_CACHE_CHECK` or `SPOTWEB_CRON_RETRIEVE` in your docker-compose or configuration to setup a cron with any of those commands. You can use `jerheij/spotweb:cron_from_env` docker image to try it out.

**Comment by Northguy** [comment]
Pulled your `jerheij/spotweb:cron_from_env` and used `SPOTWEB_CRON_RETRIEVE` in my docker-compose.yml. Works flawlesly.

**Comment by jerheij** [comment]
> Pulled your `jerheij/spotweb:cron_from_env` and used `SPOTWEB_CRON_RETRIEVE` in my docker-compose.yml. Works flawlesly.

Thanks for checking it! I have updated `README.md` and promoted it to tag `stable` and `1.3.0`.
