### ISSUE TITLE
/etc/apache2/httpd.conf error  on line 482 when using SSL

### ISSUE THREAD

**Issue by gevelr** [jerheij/docker-spotweb#7]
Hi,
I have noticed a recent error when restarting spotweb with SSL enabled. The docker image will not start with SSL anymore. 
See attached screendump. 
![Schermafbeelding 2021-09-29 163140](https://user-images.githubusercontent.com/20126280/135290007-0eb19055-712a-4552-8734-6e65419bc939.jpg)

Regards,
Rutger

**Comment by jerheij** [comment]
> Hi, I have noticed a recent error when restarting spotweb with SSL enabled. The docker image will not start with SSL anymore. See attached screendump. ![Schermafbeelding 2021-09-29 163140](https://user-images.githubusercontent.com/20126280/135290007-0eb19055-712a-4552-8734-6e65419bc939.jpg)
> 
> Regards, Rutger

Thanks for reporting this. I don't use this specific container myself any more but I will see if I can recreate this issue myself. Did you have anything custom configured with your container?

**Comment by gevelr** [comment]
No, I am just using your default container starting with:
docker run -d -p 8088:443 \
   --name=spotweb \
   --rm=true \
   -e TZ='Europe/Amsterdam' \
   -e SQL='mysql' \
   -e SSL='enabled' \
   -v '/volume1/docker/certdb:/etc/ssl/web:ro' \
   -v '/volume1/docker/spotweb/dbsettings.inc.php:/var/www/spotweb/dbsettings.inc.php:rw' \
   jerheij/spotweb:latest

**Comment by jerheij** [comment]
I just tested this with a new setup and it looks like it was caused by the container not being updated for quite some time. I have rebuild the container, which automatically uses up to date packages, so could you try again with tag `1.3.0-u1`or `stable`?

**Comment by gevelr** [comment]
It is working again (ssl enabled)!. Thanks!

**Comment by jerheij** [comment]
> It is working again (ssl enabled)!. Thanks!

Good to hear, you're welcome! 

Enjoy!
